[build]
builder = "NIXPACKS"

[deploy]
startCommand = "npm run start"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
maxRestartCount = 5

[build.setup]
nixPkgs = ["nodejs_20", "npm", "postgresql"]

[build.nixpacks]
plan = "npm install --legacy-peer-deps && npm run build"
