[build]
builder = "NIXPACKS"

[deploy]
startCommand = "npm run start"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
maxRestartCount = 5

[build.setup]
nixPkgs = ["nodejs_22", "npm", "postgresql"]

[variables]
NIXPACKS_INSTALL_CMD = "npm install --legacy-peer-deps"
NIXPACKS_BUILD_CMD = "npm run build"
