[build]
builder = "NIXPACKS"

[deploy]
startCommand = "npm run start"
healthcheckPath = "/api/payload/globals/settings"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
maxRestartCount = 10

[build.setup]
nixPkgs = ["nodejs", "npm", "postgresql"]

[build.nixpacks]
plan = "npm install && npm run build"
>>>>>>> REPLACE
